# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ca665dbd341e83999baed809d7a9e5d33cdccfe08bbdbb8117b5d16e79e843900e6704c16533d598097a475f3acdf1df4d3546d2b5227fcddb38b16eab633cf

test:
  secret_key_base: 669f91a7784f66407ad328153253f21f73dee7e3911f32b4971e899e9730e8e5d6b4db0a8c1dc55e76f62e79b00c90f557b6669d6efe4df68289ab97928dfd13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
